import java.io.*; 
import java.util.*; 
import gate.*; 
import gate.jape.*; 
import gate.creole.ontology.*; 
import gate.annotation.*; 
import gate.util.*; 
// Import: block code will be embedded here 
class <AutogeneratedActionClassName> 
         implements java.io.Serializable, gate.jape.RhsAction {
  
    private ActionContext ctx; 
    public ActionContext getActionContext() { ... } 
    public String ruleName() { .. } 
    public String phaseName() { .. } 
    public void doit( 
        gate.Document doc, 
        java.util.Map<java.lang.String, gate.AnnotationSet> bindings, 
        gate.AnnotationSet inputAS, 
        gate.AnnotationSet outputAS, 
        gate.creole.ontology.Ontology ontology) throws JapeException {
        
           // your RHS Java code will be embedded here ... 
    } 
}